#!/usr/bin/env python3
"""Aggregate test results across multiple runs into results/INDEX.md.

Usage:
    python -m automation.reporting.aggregate [--results-dir DIR] [--output FILE]
    # or directly:
    python mOSdat/automation/reporting/aggregate.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import warnings
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from .aggregate_sections import (  # noqa: F401
    flake_leaderboard,
    section_flaky as _section_flaky,
    section_matrix as _section_matrix,
    section_overview as _section_overview,
)


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class CellResult:
    status: str  # "passed", "failed", "skipped", "pending", "running"
    gpu: bool


@dataclass
class RunData:
    run_id: str          # directory name, e.g. "2026-04-14_functional"
    source: str          # "REPORT.md" or "state.json"
    version: str
    started_at: str
    last_updated: str
    phase: str
    # key -> CellResult, key format: "{vm}-{pkg}-{gpu_suffix}"
    cells: dict[str, CellResult] = field(default_factory=dict)

    @property
    def sort_key(self) -> tuple:
        m = re.match(r"(\d{4}-\d{2}-\d{2})", self.run_id)
        if m:
            try:
                return (datetime.strptime(m.group(1), "%Y-%m-%d"), self.run_id)
            except ValueError:
                pass
        return (datetime.min, self.run_id)

    @property
    def pass_count(self) -> int:
        return sum(1 for c in self.cells.values() if c.status == "passed")

    @property
    def fail_count(self) -> int:
        return sum(1 for c in self.cells.values() if c.status == "failed")

    @property
    def total_count(self) -> int:
        return len(self.cells)

    @property
    def pass_rate(self) -> float:
        if self.total_count == 0:
            return 0.0
        return self.pass_count / self.total_count * 100.0


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

def _parse_report_md(report_path: Path, run_id: str) -> RunData | None:
    """Parse a REPORT.md produced by automation/report.py."""
    text = report_path.read_text(encoding="utf-8", errors="replace")

    version_m = re.search(r"\*\*Version\*\*:\s*(.+)", text)
    version = version_m.group(1).strip() if version_m else "unknown"

    date_m = re.search(r"\*\*Date\*\*:\s*(.+)", text)
    date_str = date_m.group(1).strip() if date_m else ""

    footer_m = re.search(r"Report generated by mOSdat at (.+)\*", text)
    last_updated = footer_m.group(1).strip() if footer_m else date_str

    cells: dict[str, CellResult] = {}

    table_row = re.compile(
        r"^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|"
    )

    current_section: str | None = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("## Without GPU"):
            current_section = "no-gpu"
        elif stripped.startswith("## GPU Results"):
            current_section = "gpu"
        elif stripped.startswith("## "):
            current_section = None

        if current_section and stripped.startswith("|"):
            m = table_row.match(stripped)
            if not m:
                continue
            vm_name = m.group(1).strip()
            pkg_fmt = m.group(2).strip()
            status_raw = m.group(3).strip().lower()

            if vm_name.lower() in ("os", "----", "---") or re.match(r"^-+$", vm_name):
                continue
            if pkg_fmt.lower() in ("package", "---", "-------") or re.match(r"^-+$", pkg_fmt):
                continue

            status_clean = re.sub(r"[^\w\s]", "", status_raw).strip()
            if "passed" in status_clean or status_clean == "pass":
                status = "passed"
            elif "failed" in status_clean or status_clean == "fail":
                status = "failed"
            elif "skipped" in status_clean or status_clean == "skip":
                status = "skipped"
            elif "not run" in status_raw:
                status = "pending"
            else:
                status = status_clean or "unknown"

            gpu = (current_section == "gpu")
            key = f"{vm_name}-{pkg_fmt}-{current_section}"
            cells[key] = CellResult(status=status, gpu=gpu)

    return RunData(
        run_id=run_id,
        source="REPORT.md",
        version=version,
        started_at=date_str,
        last_updated=last_updated,
        phase="done",
        cells=cells,
    )


def _parse_state_json(state_path: Path, run_id: str) -> RunData | None:
    """Parse a state.json produced by automation/state.py."""
    try:
        data = json.loads(state_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        warnings.warn(f"[aggregate] Could not parse {state_path}: {exc}")
        return None

    version = data.get("version", "unknown")
    started_at = data.get("started_at", "")
    last_updated = data.get("last_updated", "")
    phase = data.get("phase", "unknown")

    cells: dict[str, CellResult] = {}
    for key, result in data.get("results", {}).items():
        status = result.get("status", "unknown")
        gpu = key.endswith("-gpu")
        cells[key] = CellResult(status=status, gpu=gpu)

    return RunData(
        run_id=run_id,
        source="state.json",
        version=version,
        started_at=started_at,
        last_updated=last_updated,
        phase=phase,
        cells=cells,
    )


def load_run(run_dir: Path) -> RunData | None:
    """Load a single run directory. Prefers REPORT.md; falls back to state.json."""
    run_id = run_dir.name
    report = run_dir / "REPORT.md"
    state = run_dir / "state.json"

    if report.exists():
        try:
            return _parse_report_md(report, run_id)
        except Exception as exc:
            warnings.warn(f"[aggregate] Failed to parse {report}: {exc}")

    if state.exists():
        return _parse_state_json(state, run_id)

    warnings.warn(f"[aggregate] Skipping {run_dir}: no REPORT.md or state.json")
    return None


_RUN_TYPE_SUBDIRS = ("smoke", "functional", "gpu-passthrough")


def collect_runs(results_dir: Path) -> list[RunData]:
    """Walk results_dir for run subdirectories and load each as a run.

    Supports both the flat legacy layout (results/<date>_label/) and the
    typed layout (results/{smoke,functional,gpu-passthrough}/<date>_label/).
    Typed subdirs take priority: if any of the known type subdirs exist,
    only those are scanned. Falls back to flat scan if none are present.
    """
    runs: list[RunData] = []

    typed_dirs = [results_dir / t for t in _RUN_TYPE_SUBDIRS if (results_dir / t).is_dir()]
    if typed_dirs:
        for type_dir in typed_dirs:
            type_name = type_dir.name
            for child in sorted(type_dir.iterdir()):
                if not child.is_dir():
                    continue
                run = load_run(child)
                if run is not None:
                    run.run_id = f"{type_name}/{run.run_id}"
                    runs.append(run)
    else:
        for child in sorted(results_dir.iterdir()):
            if not child.is_dir():
                continue
            run = load_run(child)
            if run is not None:
                runs.append(run)

    return sorted(runs, key=lambda r: r.sort_key)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_index(results_dir: Path, output: Path) -> None:
    runs = collect_runs(results_dir)

    if not runs:
        print(f"[aggregate] WARNING: No parseable runs found in {results_dir}", file=sys.stderr)

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    last_run_ts = runs[-1].last_updated[:19] if runs else "N/A"

    parts = [
        "# Test Results Index\n",
        f"**Generated**: {now}  \n"
        f"**Total runs aggregated**: {len(runs)}  \n"
        f"**Last run timestamp**: {last_run_ts}  \n"
        f"**Results directory**: `{results_dir}`\n",
        _section_overview(runs),
        _section_matrix(runs),
        _section_flaky(runs),
        "---\n\n_Generated by `automation/aggregate.py`_\n",
    ]

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts), encoding="utf-8")
    print(f"[aggregate] Written: {output}")
    if not runs:
        print("[aggregate] 0 runs — INDEX.md created with empty tables.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Aggregate test run results into INDEX.md",
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=Path("results"),
        help="Directory containing run subdirectories (default: results/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path for INDEX.md (default: <results-dir>/INDEX.md)",
    )
    args = parser.parse_args()

    results_dir: Path = args.results_dir
    output: Path = args.output if args.output is not None else results_dir / "INDEX.md"

    if not results_dir.exists():
        print(f"[aggregate] ERROR: results-dir does not exist: {results_dir}", file=sys.stderr)
        sys.exit(1)

    generate_index(results_dir, output)


if __name__ == "__main__":
    main()
