#!/usr/bin/env python3
"""Aggregate test results across multiple runs into results/INDEX.md.

Usage:
    python -m automation.reporting.aggregate [--results-dir DIR] [--output FILE]
    # or directly:
    python mOSdat/automation/reporting/aggregate.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import warnings
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from statistics import median


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class CellResult:
    status: str  # "passed", "failed", "skipped", "pending", "running"
    gpu: bool


@dataclass
class RunData:
    run_id: str          # directory name, e.g. "2026-04-14_functional"
    source: str          # "REPORT.md" or "state.json"
    version: str
    started_at: str
    last_updated: str
    phase: str
    # key -> CellResult, key format: "{vm}-{pkg}-{gpu_suffix}"
    cells: dict[str, CellResult] = field(default_factory=dict)

    @property
    def sort_key(self) -> tuple:
        # Try to parse YYYY-MM-DD prefix for chronological sort
        m = re.match(r"(\d{4}-\d{2}-\d{2})", self.run_id)
        if m:
            try:
                return (datetime.strptime(m.group(1), "%Y-%m-%d"), self.run_id)
            except ValueError:
                pass
        return (datetime.min, self.run_id)

    @property
    def pass_count(self) -> int:
        return sum(1 for c in self.cells.values() if c.status == "passed")

    @property
    def fail_count(self) -> int:
        return sum(1 for c in self.cells.values() if c.status == "failed")

    @property
    def total_count(self) -> int:
        return len(self.cells)

    @property
    def pass_rate(self) -> float:
        if self.total_count == 0:
            return 0.0
        return self.pass_count / self.total_count * 100.0


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

def _parse_report_md(report_path: Path, run_id: str) -> RunData | None:
    """Parse a REPORT.md produced by automation/report.py."""
    text = report_path.read_text(encoding="utf-8", errors="replace")

    # Extract version
    version_m = re.search(r"\*\*Version\*\*:\s*(.+)", text)
    version = version_m.group(1).strip() if version_m else "unknown"

    # Extract date from header
    date_m = re.search(r"\*\*Date\*\*:\s*(.+)", text)
    date_str = date_m.group(1).strip() if date_m else ""

    # Extract footer timestamp (ISO format)
    footer_m = re.search(r"Report generated by mOSdat at (.+)\*", text)
    last_updated = footer_m.group(1).strip() if footer_m else date_str

    cells: dict[str, CellResult] = {}

    # Parse "Without GPU Results" and "GPU Results" tables
    # Table row format: | OS | Package | Status emoji+text | Exit Code |
    table_row = re.compile(
        r"^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|"
    )

    current_section: str | None = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("## Without GPU"):
            current_section = "no-gpu"
        elif stripped.startswith("## GPU Results"):
            current_section = "gpu"
        elif stripped.startswith("## "):
            current_section = None

        if current_section and stripped.startswith("|"):
            m = table_row.match(stripped)
            if not m:
                continue
            vm_name = m.group(1).strip()
            pkg_fmt = m.group(2).strip()
            status_raw = m.group(3).strip().lower()

            # Skip header rows (case-insensitive) and separator rows (all dashes)
            if vm_name.lower() in ("os", "----", "---") or re.match(r"^-+$", vm_name):
                continue
            if pkg_fmt.lower() in ("package", "---", "-------") or re.match(r"^-+$", pkg_fmt):
                continue

            # Normalise status: strip emojis and leading/trailing noise
            status_clean = re.sub(r"[^\w\s]", "", status_raw).strip()
            if "passed" in status_clean or status_clean == "pass":
                status = "passed"
            elif "failed" in status_clean or status_clean == "fail":
                status = "failed"
            elif "skipped" in status_clean or status_clean == "skip":
                status = "skipped"
            elif "not run" in status_raw:
                status = "pending"
            else:
                status = status_clean or "unknown"

            gpu = (current_section == "gpu")
            key = f"{vm_name}-{pkg_fmt}-{current_section}"
            cells[key] = CellResult(status=status, gpu=gpu)

    return RunData(
        run_id=run_id,
        source="REPORT.md",
        version=version,
        started_at=date_str,
        last_updated=last_updated,
        phase="done",
        cells=cells,
    )


def _parse_state_json(state_path: Path, run_id: str) -> RunData | None:
    """Parse a state.json produced by automation/state.py."""
    try:
        data = json.loads(state_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        warnings.warn(f"[aggregate] Could not parse {state_path}: {exc}")
        return None

    version = data.get("version", "unknown")
    started_at = data.get("started_at", "")
    last_updated = data.get("last_updated", "")
    phase = data.get("phase", "unknown")

    cells: dict[str, CellResult] = {}
    for key, result in data.get("results", {}).items():
        status = result.get("status", "unknown")
        # Key format from state.py: "{vm_name}-{package_format}-{gpu|no-gpu}"
        gpu = key.endswith("-gpu")
        cells[key] = CellResult(status=status, gpu=gpu)

    return RunData(
        run_id=run_id,
        source="state.json",
        version=version,
        started_at=started_at,
        last_updated=last_updated,
        phase=phase,
        cells=cells,
    )


def load_run(run_dir: Path) -> RunData | None:
    """Load a single run directory. Prefers REPORT.md; falls back to state.json."""
    run_id = run_dir.name
    report = run_dir / "REPORT.md"
    state = run_dir / "state.json"

    if report.exists():
        try:
            return _parse_report_md(report, run_id)
        except Exception as exc:
            warnings.warn(f"[aggregate] Failed to parse {report}: {exc}")

    if state.exists():
        return _parse_state_json(state, run_id)

    warnings.warn(f"[aggregate] Skipping {run_dir}: no REPORT.md or state.json")
    return None


_RUN_TYPE_SUBDIRS = ("smoke", "functional", "gpu-passthrough")


def collect_runs(results_dir: Path) -> list[RunData]:
    """Walk results_dir for run subdirectories and load each as a run.

    Supports both the flat legacy layout (results/<date>_label/) and the
    typed layout (results/{smoke,functional,gpu-passthrough}/<date>_label/).
    Typed subdirs take priority: if any of the known type subdirs exist,
    only those are scanned. Falls back to flat scan if none are present.
    """
    runs: list[RunData] = []

    typed_dirs = [results_dir / t for t in _RUN_TYPE_SUBDIRS if (results_dir / t).is_dir()]
    if typed_dirs:
        # Typed layout: walk each run-type subdir, prefix run_id with type name
        for type_dir in typed_dirs:
            type_name = type_dir.name
            for child in sorted(type_dir.iterdir()):
                if not child.is_dir():
                    continue
                run = load_run(child)
                if run is not None:
                    run.run_id = f"{type_name}/{run.run_id}"
                    runs.append(run)
    else:
        # Legacy flat layout: runs sit directly under results_dir
        for child in sorted(results_dir.iterdir()):
            if not child.is_dir():
                continue
            run = load_run(child)
            if run is not None:
                runs.append(run)

    return sorted(runs, key=lambda r: r.sort_key)


# ---------------------------------------------------------------------------
# Markdown generation helpers
# ---------------------------------------------------------------------------

def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    """Render a simple ASCII markdown table."""
    # Compute column widths
    widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            if i < len(widths):
                widths[i] = max(widths[i], len(cell))

    def fmt_row(cells: list[str]) -> str:
        parts = []
        for i, cell in enumerate(cells):
            w = widths[i] if i < len(widths) else len(cell)
            parts.append(cell.ljust(w))
        return "| " + " | ".join(parts) + " |"

    sep = "| " + " | ".join("-" * w for w in widths) + " |"
    lines = [fmt_row(headers), sep]
    for row in rows:
        lines.append(fmt_row(row))
    return "\n".join(lines)


def _status_char(status: str) -> str:
    mapping = {
        "passed": "PASS",
        "failed": "FAIL",
        "skipped": "SKIP",
        "pending": "-",
        "running": "RUN",
    }
    return mapping.get(status, status.upper()[:4] if status else "?")


# ---------------------------------------------------------------------------
# Report sections
# ---------------------------------------------------------------------------

def _section_overview(runs: list[RunData]) -> str:
    lines = ["## Overview\n"]
    rows = []
    for r in runs:
        rate = f"{r.pass_rate:.0f}%" if r.total_count else "N/A"
        rows.append([
            r.run_id,
            r.version,
            str(r.pass_count),
            str(r.fail_count),
            str(r.total_count),
            rate,
            r.source,
            r.last_updated[:19] if r.last_updated else "",
        ])
    table = _md_table(
        ["Run", "Version", "Pass", "Fail", "Total", "Pass%", "Source", "Last Updated"],
        rows,
    )
    lines.append(table)
    lines.append("")
    return "\n".join(lines)


def _section_matrix(runs: list[RunData]) -> str:
    """OS x Package x GPU x Scenario matrix."""
    # Collect all unique cell keys across all runs
    all_keys: list[str] = []
    seen: set[str] = set()
    for r in runs:
        for k in r.cells:
            if k not in seen:
                all_keys.append(k)
                seen.add(k)
    all_keys.sort()

    if not all_keys:
        return "## Matrix\n\n_No test cells found._\n"

    lines = ["## Matrix\n"]
    lines.append("Rows = runs. Columns = OS-Package-GPU combos. Values = PASS/FAIL/SKIP/-.\n")

    # Truncate long key names for column headers
    col_headers = ["Run"] + [k for k in all_keys]
    rows = []
    for r in runs:
        row = [r.run_id]
        for k in all_keys:
            cell = r.cells.get(k)
            row.append(_status_char(cell.status) if cell else "-")
        rows.append(row)

    table = _md_table(col_headers, rows)
    lines.append(table)
    lines.append("")
    return "\n".join(lines)


def _section_flaky(runs: list[RunData]) -> str:
    """Cells that passed in some runs and failed in others."""
    all_keys: set[str] = set()
    for r in runs:
        all_keys.update(r.cells.keys())

    flaky: list[tuple[str, list[str], list[str]]] = []
    for key in sorted(all_keys):
        passed_in = []
        failed_in = []
        for r in runs:
            cell = r.cells.get(key)
            if cell is None:
                continue
            if cell.status == "passed":
                passed_in.append(r.run_id)
            elif cell.status == "failed":
                failed_in.append(r.run_id)
        if passed_in and failed_in:
            flaky.append((key, passed_in, failed_in))

    if not flaky:
        return "## Flaky Tests\n\n_No flaky tests detected._\n"

    lines = ["## Flaky Tests\n"]
    lines.append("Tests that passed in some runs and failed in others.\n")
    rows = []
    for key, passed_in, failed_in in flaky:
        rows.append([key, str(len(passed_in)), str(len(failed_in)),
                     ", ".join(passed_in[:3]) + ("..." if len(passed_in) > 3 else ""),
                     ", ".join(failed_in[:3]) + ("..." if len(failed_in) > 3 else "")])
    table = _md_table(
        ["Cell", "Pass Count", "Fail Count", "Passed In", "Failed In"],
        rows,
    )
    lines.append(table)
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Flakiness leaderboard (B5)
# ---------------------------------------------------------------------------

def flake_leaderboard(results_root: Path) -> str:
    """Aggregate retry rates across ALL past functional runs.

    Walks results_root/functional for all dated run dirs, groups events by step label,
    counts retries and failures, aggregates across runs, and returns a markdown table
    ranked by retry_rate.

    Args:
        results_root: Path to results directory (contains "functional" subdir)

    Returns:
        Markdown string with flakiness leaderboard table. Empty report if no runs found.
    """
    functional_dir = results_root / "functional"

    if not functional_dir.exists():
        return f"# Flakiness Leaderboard\n\nNo functional runs found under {results_root}\n"

    # Collect all run directories matching pattern: YYYY-MM-DD*
    run_dirs = []
    for item in sorted(functional_dir.iterdir()):
        if item.is_dir() and re.match(r"\d{4}-\d{2}-\d{2}", item.name):
            run_dirs.append(item)

    if not run_dirs:
        return f"# Flakiness Leaderboard\n\nNo functional runs found under {results_root}\n"

    # Data structure: {step_label: {"runs": set, "retries": count, "failures": count, "attempts": []}}
    step_stats: dict[str, dict] = {}

    # Walk all run dirs looking for events.jsonl in VM subdirs
    for run_dir in run_dirs:
        for vm_dir in run_dir.iterdir():
            if not vm_dir.is_dir():
                continue
            events_file = vm_dir / "events.jsonl"
            if not events_file.exists():
                continue

            # Parse events.jsonl
            try:
                with events_file.open("r", encoding="utf-8", errors="replace") as f:
                    for line in f:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            event = json.loads(line)
                        except json.JSONDecodeError:
                            warnings.warn(f"[flake_leaderboard] Malformed JSON in {events_file}: {line[:100]}")
                            continue

                        # Track step_start → step_end + retry events per step
                        if event.get("event") == "step_start":
                            step_num = event.get("step_num")
                            label = event.get("label", "")
                            # Normalize label: truncate to first 60 chars to avoid duplicates from ellipsis
                            label_key = label[:60] if label else f"step_{step_num}"

                            if label_key not in step_stats:
                                step_stats[label_key] = {
                                    "runs": set(),
                                    "retries": 0,
                                    "failures": 0,
                                    "attempts": [],
                                }
                            # Register this run as having encountered this step
                            step_stats[label_key]["runs"].add(run_dir.name)

                        elif event.get("event") == "retry":
                            step_num = event.get("step_num")
                            label = event.get("label", "")
                            label_key = label[:60] if label else f"step_{step_num}"
                            if label_key in step_stats:
                                step_stats[label_key]["retries"] += 1

                        elif event.get("event") == "step_end":
                            step_num = event.get("step_num")
                            label = event.get("label", "")
                            label_key = label[:60] if label else f"step_{step_num}"
                            status = event.get("status", "")
                            attempts = event.get("attempts", 1)

                            if label_key in step_stats:
                                if status == "failed":
                                    step_stats[label_key]["failures"] += 1
                                if attempts:
                                    step_stats[label_key]["attempts"].append(attempts)

            except OSError as exc:
                warnings.warn(f"[flake_leaderboard] Could not read {events_file}: {exc}")
                continue

    if not step_stats:
        return f"# Flakiness Leaderboard\n\nNo events found in {results_root}\n"

    # Compute metrics for each step
    leaderboard: list[tuple[str, int, int, int, float, float, int]] = []
    for label, stats in step_stats.items():
        runs_total = len(stats["runs"])
        # Exclude steps with <2 runs (not statistically meaningful)
        if runs_total < 2:
            continue

        retries_total = stats["retries"]
        failures_total = stats["failures"]
        attempts_list = stats["attempts"]

        retry_rate = retries_total / runs_total if runs_total > 0 else 0.0
        failure_rate = failures_total / runs_total if runs_total > 0 else 0.0
        median_attempts = int(median(attempts_list)) if attempts_list else 1

        leaderboard.append((
            label,
            runs_total,
            retries_total,
            failures_total,
            retry_rate,
            failure_rate,
            median_attempts,
        ))

    # Sort by retry_rate descending (most flaky first)
    leaderboard.sort(key=lambda x: x[4], reverse=True)

    # Cap at top 30 entries
    leaderboard = leaderboard[:30]

    # Render as markdown table
    now = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    rows = []
    for label, runs, retries, failures, retry_rate, failure_rate, med_attempts in leaderboard:
        rows.append([
            label,
            str(runs),
            f"{retry_rate:.2f}",
            f"{failure_rate:.2f}",
            str(med_attempts),
        ])

    table = _md_table(
        ["Step", "Runs", "Retry rate", "Failure rate", "Median attempts"],
        rows,
    ) if rows else "_No steps with sufficient history (minimum 2 runs)._"

    lines = [
        "# Flakiness Leaderboard\n",
        f"Generated: {now}\n"
        f"Runs analyzed: {len(run_dirs)}\n",
        table,
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_index(results_dir: Path, output: Path) -> None:
    runs = collect_runs(results_dir)

    if not runs:
        print(f"[aggregate] WARNING: No parseable runs found in {results_dir}", file=sys.stderr)

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    last_run_ts = runs[-1].last_updated[:19] if runs else "N/A"

    parts = [
        "# Test Results Index\n",
        f"**Generated**: {now}  \n"
        f"**Total runs aggregated**: {len(runs)}  \n"
        f"**Last run timestamp**: {last_run_ts}  \n"
        f"**Results directory**: `{results_dir}`\n",
        _section_overview(runs),
        _section_matrix(runs),
        _section_flaky(runs),
        "---\n\n_Generated by `automation/aggregate.py`_\n",
    ]

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts), encoding="utf-8")
    print(f"[aggregate] Written: {output}")
    if not runs:
        print("[aggregate] 0 runs — INDEX.md created with empty tables.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Aggregate test run results into INDEX.md",
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=Path("results"),
        help="Directory containing run subdirectories (default: results/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path for INDEX.md (default: <results-dir>/INDEX.md)",
    )
    args = parser.parse_args()

    results_dir: Path = args.results_dir
    output: Path = args.output if args.output is not None else results_dir / "INDEX.md"

    if not results_dir.exists():
        print(f"[aggregate] ERROR: results-dir does not exist: {results_dir}", file=sys.stderr)
        sys.exit(1)

    generate_index(results_dir, output)


if __name__ == "__main__":
    main()
