"""Triage and Author Workbench HTML for the live dashboard."""

from __future__ import annotations

_TRIAGE_HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>mOSdat Live Triage</title>
<style>
:root{--bg:#0b0f14;--panel:#121821;--panel2:#182130;--text:#e8eef6;--muted:#9aa7b8;--border:#2a3547;--ok:#3fb950;--fail:#ff6b6b;--run:#58a6ff;--stale:#f0b429}
*{box-sizing:border-box}body{margin:0;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--text)}
header{position:sticky;top:0;z-index:10;background:rgba(11,15,20,.96);border-bottom:1px solid var(--border);padding:12px 18px}
.top{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.title{font-weight:750;font-size:18px;margin-right:8px}
.nav{color:var(--text);text-decoration:none;border:1px solid var(--border);border-radius:6px;padding:6px 10px;background:var(--panel2);font-size:12px}
.pill{border:1px solid var(--border);border-radius:999px;padding:4px 10px;color:var(--muted);font-size:12px}.pill.pass{color:var(--ok);border-color:rgba(63,185,80,.45)}.pill.fail{color:var(--fail);border-color:rgba(255,107,107,.45)}.pill.running{color:var(--run);border-color:rgba(88,166,255,.45)}.pill.stale,.pill.partial{color:var(--stale);border-color:rgba(240,180,41,.45)}.pill.skipped{color:var(--muted)}
main{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:16px;padding:16px}section{background:var(--panel);border:1px solid var(--border);border-radius:8px;min-width:0}.section-head{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:12px 14px;border-bottom:1px solid var(--border)}h2{font-size:14px;margin:0}.matrix{overflow:auto}
table{border-collapse:collapse;width:100%;min-width:720px}th,td{border-bottom:1px solid var(--border);padding:8px;text-align:left;font-size:12px;vertical-align:middle}th{color:var(--muted);font-weight:650;background:var(--panel2);position:sticky;top:0}.vm-name{font-weight:700}.small{color:var(--muted);font-size:12px}
.step-row{display:flex;gap:4px;flex-wrap:wrap}.cell{width:28px;height:28px;border-radius:6px;border:1px solid var(--border);display:inline-flex;align-items:center;justify-content:center;cursor:pointer;color:var(--text);font-size:11px;background:transparent}.cell.pass{background:rgba(63,185,80,.18);border-color:rgba(63,185,80,.55)}.cell.fail{background:rgba(255,107,107,.18);border-color:rgba(255,107,107,.65)}.cell.running{background:rgba(88,166,255,.18);border-color:rgba(88,166,255,.6)}.cell.skipped{background:rgba(154,167,184,.12);color:var(--muted)}.cell.stale,.cell.partial{background:rgba(240,180,41,.18);border-color:rgba(240,180,41,.6)}.cell.slow{box-shadow:inset 0 -3px 0 rgba(240,180,41,.9)}.cell.hot{box-shadow:inset 0 -3px 0 rgba(255,107,107,.95)}
.thumb{width:74px;height:44px;object-fit:contain;border:1px solid var(--border);border-radius:6px;background:#05070a;cursor:zoom-in}
.media-links{margin-top:4px}.media-links a{color:var(--run);text-decoration:none}.media-links a:hover{text-decoration:underline}
.fail-list{padding:10px;display:flex;flex-direction:column;gap:10px;max-height:calc(100vh - 150px);overflow:auto}.fail-card{border:1px solid rgba(255,107,107,.45);background:rgba(255,107,107,.08);border-radius:8px;padding:10px;cursor:pointer}.fail-card img{width:100%;max-height:160px;object-fit:contain;border:1px solid var(--border);border-radius:6px;margin-top:8px;background:#05070a}
.drawer{position:fixed;right:0;top:0;bottom:0;width:min(720px,96vw);background:#0f151f;border-left:1px solid var(--border);z-index:30;transform:translateX(100%);transition:.18s transform;overflow:auto}.drawer.open{transform:translateX(0)}.drawer-head{position:sticky;top:0;background:#0f151f;border-bottom:1px solid var(--border);padding:14px;display:flex;justify-content:space-between;gap:12px}.drawer-body{padding:14px}button{background:var(--panel2);color:var(--text);border:1px solid var(--border);border-radius:6px;padding:6px 10px;cursor:pointer}.event{border:1px solid var(--border);border-radius:6px;padding:8px;margin:8px 0;background:rgba(255,255,255,.025)}.shots{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.shots img{width:180px;height:110px;object-fit:contain;border:1px solid var(--border);border-radius:6px;background:#05070a;cursor:zoom-in}.empty{padding:28px;color:var(--muted);text-align:center}
#lightbox{display:none;position:fixed;inset:0;z-index:50;background:rgba(0,0,0,.86);align-items:center;justify-content:center;padding:20px}#lightbox img{max-width:96vw;max-height:92vh;border:1px solid var(--border)}@media(max-width:980px){main{grid-template-columns:1fr}}
</style>
</head>
<body>
<header><div class="top"><div class="title">mOSdat Live Triage</div><a class="nav" href="/author">Author Workbench</a><span id="conn" class="pill stale">connecting</span><span id="runs" class="pill">0 runs</span><span id="running" class="pill running">0 running</span><span id="pass" class="pill pass">0 pass</span><span id="fail" class="pill fail">0 fail</span><span id="stale" class="pill stale">0 stale</span><span id="updated" class="pill">updated never</span><label class="small">Run <select id="run-filter" onchange="setRunFilter(this.value)"><option value="latest">Latest</option><option value="all">All</option></select></label><button onclick="loadState()">Refresh</button></div><div id="freshness" class="small" style="margin-top:8px">No run loaded.</div></header>
<main><section><div class="section-head"><h2>Matrix Overview</h2><span class="small">click a step for timeline</span></div><div id="matrix" class="matrix"><div class="empty">Loading state…</div></div></section><section><div class="section-head"><h2>Failures</h2><span id="failure-count" class="small">0</span></div><div id="failures" class="fail-list"><div class="empty">No failures</div></div></section></main>
<aside id="drawer" class="drawer"><div class="drawer-head"><div><strong id="drawer-title">Timeline</strong><div id="drawer-sub" class="small"></div></div><button onclick="closeDrawer()">Close</button></div><div id="drawer-body" class="drawer-body"></div></aside>
<div id="lightbox" onclick="closeLightbox()"><img id="lightbox-img" src="" alt="screenshot"><video id="lightbox-video" controls style="display:none;max-width:96vw;max-height:92vh;border:1px solid var(--border)"></video></div>
<script>
let state=null;let runFilter='latest';function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmtAge(sec){if(sec==null)return'-';if(sec<60)return`${sec}s`;return`${Math.floor(sec/60)}m ${sec%60}s`;}
function cls(status){return['pass','fail','running','stale','partial','skipped'].includes(status)?status:''}
async function loadState(){const res=await fetch('/api/state',{cache:'no-store'});state=await res.json();render();}
function visibleRuns(){const runs=state?.runs||[];if(runFilter==='all')return runs;if(runFilter==='latest')return runs.slice(0,1);return runs.filter(r=>r.name===runFilter)}
function setRunFilter(value){runFilter=value;render()}
function updateRunFilter(){const sel=document.getElementById('run-filter');const current=sel.value||runFilter;sel.innerHTML='<option value="latest">Latest</option><option value="all">All</option>'+((state?.runs||[]).slice(0,20).map(r=>`<option value="${esc(r.name)}">${esc(r.name)}</option>`).join(''));sel.value=[...sel.options].some(o=>o.value===current)?current:'latest';runFilter=sel.value}
function visibleTotals(){const runs=visibleRuns();let t={runs:runs.length,running:0,pass:0,fail:0,stale:0};for(const run of runs)for(const vm of run.vms||[])t[vm.status]=(t[vm.status]||0)+1;return t}
function heat(step){const ms=step.duration_ms||0;if(ms>90000)return'hot';if(ms>30000)return'slow';return''}
function render(){if(!state)return;updateRunFilter();const t=visibleTotals();for(const [id,val] of Object.entries({runs:`${t.runs||0} runs`,running:`${t.running||0} running`,pass:`${t.pass||0} pass`,fail:`${t.fail||0} fail`,stale:`${t.stale||0} stale`}))document.getElementById(id).textContent=val;document.getElementById('updated').textContent=`updated ${new Date(state.generated_at).toLocaleTimeString()}`;renderFreshness();renderMatrix();renderFailures();}
function renderFreshness(){const runs=visibleRuns();if(!runs.length){document.getElementById('freshness').textContent='No run selected.';return}const run=runs[0];document.getElementById('freshness').textContent=runFilter==='all'?`Browsing all runs · ${state.totals.vms||0} VMs total`:`Watching ${run.name} · ${run.status} · last event ${fmtAge(run.age_seconds)} ago · ${run.vms.length} VM(s)`}
function renderMatrix(){const rows=[];for(const run of visibleRuns())for(const vm of run.vms||[]){const shot=vm.latest_screenshot;const rec=vm.recording||{};const mp4=rec.mp4?.url||'';const gif=rec.gif?.url||'';const links=(mp4||gif)?`<div class="small media-links">${mp4?`<a href="#" onclick="openMedia('${esc(mp4)}','video');return false">play video</a> · <a href="${esc(mp4)}" target="_blank" rel="noopener">open mp4</a>`:''}${mp4&&gif?' · ':''}${gif?`<a href="${esc(gif)}" target="_blank" rel="noopener">gif</a>`:''}</div>`:'';const latest=shot?`<img class="thumb" src="${esc(shot.url)}" onclick="openLightbox('${esc(shot.url)}')" loading="lazy">${links}`:(links||'<span class="small">-</span>');rows.push(`<tr><td><div class="vm-name">${esc(vm.vm)}</div><div class="small">${esc(run.name)}</div></td><td><span class="pill ${cls(vm.status)}">${esc(vm.status)}</span></td><td>${latest}</td><td>${vm.current_step?`step ${esc(vm.current_step.step_num)} <span class="small">${esc(vm.current_step.kind)}</span>`:'<span class="small">-</span>'}</td><td>${fmtAge(vm.duration_seconds)}</td><td><div class="step-row">${(vm.steps||[]).map(step=>`<button class="cell ${cls(step.status)} ${heat(step)}" title="step ${esc(step.step_num)} ${esc(step.status)} ${esc(step.duration_ms??'-')}ms" onclick="openTimeline('${esc(run.name)}','${esc(vm.vm)}','${esc(step.step_num)}')">${esc(step.step_num)}</button>`).join('')}</div></td></tr>`)}document.getElementById('matrix').innerHTML=rows.length?`<table><thead><tr><th>VM</th><th>Status</th><th>Latest</th><th>Current</th><th>Total runtime</th><th>Steps</th></tr></thead><tbody>${rows.join('')}</tbody></table>`:'<div class="empty">No functional runs found.</div>'}
function renderFailures(){const names=new Set(visibleRuns().map(r=>r.name));const failures=(state.failures||[]).filter(f=>runFilter==='all'||names.has(f.run));document.getElementById('failure-count').textContent=String(failures.length);document.getElementById('failures').innerHTML=failures.length?failures.map(f=>`<div class="fail-card" onclick="openTimeline('${esc(f.run)}','${esc(f.vm)}','${esc(f.step_num)}')"><div><strong>${esc(f.vm)}</strong> step ${esc(f.step_num)}</div><div class="small">${esc(f.run)} · <span class="pill fail">${esc(f.cause||'step failed')}</span> · attempts ${esc(f.attempts??'-')} · ${esc(f.duration_ms??'-')}ms</div>${f.question?`<div class="small">Q: ${esc(f.question)}</div>`:''}${f.answer?`<div class="small">A: ${esc(f.answer)}</div>`:''}${f.screenshot?`<img src="${esc(f.screenshot.url)}" loading="lazy">`:''}</div>`).join(''):'<div class="empty">No failures</div>'}
function findVm(runName,vmName){for(const run of state.runs||[])if(run.name===runName)for(const vm of run.vms||[])if(vm.vm===vmName)return vm;return null}
function openTimeline(runName,vmName,stepNum){const vm=findVm(runName,vmName);if(!vm)return;const steps=stepNum===''?vm.steps:vm.steps.filter(s=>String(s.step_num)===String(stepNum));document.getElementById('drawer-title').textContent=`${vmName} timeline`;document.getElementById('drawer-sub').textContent=`${runName} · ${vm.status} · last ${fmtAge(vm.age_seconds)}`;document.getElementById('drawer-body').innerHTML=steps.map(step=>`<div class="event"><div><strong>Step ${esc(step.step_num)}</strong> <span class="pill ${cls(step.status)}">${esc(step.status)}</span></div><div class="small">${esc(step.kind||'')} ${esc(step.label||'')} · ${esc(step.duration_ms??'-')}ms · attempts ${esc(step.attempts??'-')}</div>${(step.events||[]).map(e=>`<div class="event"><div class="small">${esc(e.ts||'')} · ${esc(e.event||'')}</div>${eventBody(e)}</div>`).join('')}<div class="shots">${(step.screenshots||[]).map(s=>`<img src="${esc(s.url)}" title="${esc(s.filename)}" onclick="openLightbox('${esc(s.url)}')" loading="lazy">`).join('')}</div></div>`).join('')||'<div class="empty">No events for this step.</div>';document.getElementById('drawer').classList.add('open')}
function eventBody(e){const bits=[];if(e.event==='app_crashed'){const detail=[e.process?`process: ${esc(e.process)}`:'',e.cleanup_clicked!=null?`cleanup_clicked: ${esc(e.cleanup_clicked)}`:''].filter(Boolean).join(', ');return`<div style="color:var(--fail);font-weight:700">&#x1F4A5; APP CRASHED &mdash; ${esc(e.source||'')}${detail?` (${detail})`:''}</div>`}if(e.event==='process_probe'){const color=e.running===false?'color:var(--fail)':'';return`<div class="small" style="${color}">process: ${esc(e.process||'')} running=${esc(String(e.running??''))}</div>`}if(e.event==='apport_cancel_click'){const coords=Array.isArray(e.coords)?`(${e.coords[0]},${e.coords[1]})`:'?';return`<div class="small">apport Cancel clicked @ ${esc(coords)}</div>`}if(e.question)bits.push(`Q: ${esc(e.question)}`);if(e.answer)bits.push(`A: ${esc(e.answer)}`);if(e.status)bits.push(`status: ${esc(e.status)}`);if(e.latency_ms)bits.push(`latency: ${esc(e.latency_ms)}ms`);return bits.length?`<div>${bits.join('<br>')}</div>`:''}
function closeDrawer(){document.getElementById('drawer').classList.remove('open')}function openLightbox(url){const img=document.getElementById('lightbox-img');const vid=document.getElementById('lightbox-video');vid.pause();vid.removeAttribute('src');vid.style.display='none';img.style.display='block';img.src=url;document.getElementById('lightbox').style.display='flex'}function openMedia(url,type){const img=document.getElementById('lightbox-img');const vid=document.getElementById('lightbox-video');img.style.display='none';img.src='';vid.style.display='block';vid.src=url;vid.load();document.getElementById('lightbox').style.display='flex'}function closeLightbox(){const lb=document.getElementById('lightbox');const img=document.getElementById('lightbox-img');const vid=document.getElementById('lightbox-video');lb.style.display='none';img.src='';vid.pause();vid.removeAttribute('src');vid.style.display='none';img.style.display='block'}
const es=new EventSource('/stream');es.onopen=()=>{const c=document.getElementById('conn');c.textContent='connected';c.className='pill pass'};es.onerror=()=>{const c=document.getElementById('conn');c.textContent='disconnected';c.className='pill fail'};es.onmessage=()=>loadState();loadState();setInterval(loadState,5000);
</script></body></html>
"""

_AUTHOR_HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>mOSdat Author Workbench</title>
<style>
:root{--bg:#0b0f14;--panel:#121821;--panel2:#182130;--text:#e8eef6;--muted:#9aa7b8;--border:#2a3547;--ok:#3fb950;--fail:#ff6b6b;--run:#58a6ff}
*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--text)}
header{height:56px;display:flex;align-items:center;gap:12px;padding:0 16px;border-bottom:1px solid var(--border);background:#0b0f14}
.title{font-weight:750;font-size:18px}.nav{color:var(--text);text-decoration:none;border:1px solid var(--border);border-radius:6px;padding:6px 10px;background:var(--panel2);font-size:12px}.small{color:var(--muted);font-size:12px}.spacer{flex:1}
button{background:var(--panel2);color:var(--text);border:1px solid var(--border);border-radius:6px;padding:7px 10px;cursor:pointer;transition:.15s opacity,.15s border-color,.15s transform}button.primary{background:#14304f;border-color:rgba(88,166,255,.6)}button:disabled{opacity:.45;cursor:not-allowed}body.author-busy button[data-op]{pointer-events:none}.op-card{display:none;border:1px solid rgba(88,166,255,.45);background:rgba(88,166,255,.08);border-radius:8px;padding:10px;gap:8px;align-items:flex-start}.op-card.active,.op-card.done,.op-card.error{display:flex}.op-card.done{border-color:rgba(63,185,80,.55);background:rgba(63,185,80,.08)}.op-card.error{border-color:rgba(255,107,107,.55);background:rgba(255,107,107,.08)}.spinner{width:16px;height:16px;border:2px solid rgba(88,166,255,.25);border-top-color:var(--run);border-radius:50%;animation:spin .9s linear infinite;flex:0 0 auto;margin-top:2px}.op-card.done .spinner,.op-card.error .spinner{animation:none;border-color:currentColor}.op-title{font-weight:700}.op-detail{color:var(--muted);font-size:12px;margin-top:2px}.status.busy{color:var(--run);border-color:rgba(88,166,255,.65);box-shadow:0 0 0 3px rgba(88,166,255,.08)}.screen.busy:after{content:attr(data-busy);position:absolute;left:14px;bottom:14px;right:14px;padding:10px 12px;border:1px solid rgba(88,166,255,.45);border-radius:8px;background:rgba(5,7,10,.88);color:var(--text);font-size:13px;backdrop-filter:blur(4px)}@keyframes spin{to{transform:rotate(360deg)}}
input,select,textarea{width:100%;background:var(--panel2);color:var(--text);border:1px solid var(--border);border-radius:6px;padding:8px}textarea{min-height:112px;resize:vertical}
main{height:calc(100vh - 56px);display:grid;grid-template-columns:320px minmax(0,1fr) 380px;gap:12px;padding:12px}
.panel{min-height:0;background:var(--panel);border:1px solid var(--border);border-radius:8px;overflow:auto}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:12px;border-bottom:1px solid var(--border)}.panel-body{padding:12px;display:flex;flex-direction:column;gap:10px}
.row{display:flex;gap:8px}.row>*{flex:1}.screen{position:relative;min-height:0;height:100%;display:flex;align-items:center;justify-content:center;background:#05070a;border:1px solid var(--border);border-radius:8px;overflow:hidden}.screen img{max-width:100%;max-height:100%;object-fit:contain}.target{position:absolute;width:28px;height:28px;transform:translate(-50%,-50%);pointer-events:none}.target:before,.target:after{content:"";position:absolute;left:50%;top:50%;width:28px;height:2px;background:var(--fail);transform-origin:center}.target:before{transform:translate(-50%,-50%) rotate(45deg)}.target:after{transform:translate(-50%,-50%) rotate(-45deg)}
pre{white-space:pre-wrap;background:#070b11;border:1px solid var(--border);border-radius:6px;padding:9px;min-height:120px;overflow:auto}.status{border:1px solid var(--border);border-radius:999px;padding:4px 10px;color:var(--muted);font-size:12px}.status.running{color:var(--ok);border-color:rgba(63,185,80,.5)}.status.stopped{color:var(--muted)}.status.unknown{color:#f0b429;border-color:rgba(240,180,41,.5)}
@media(max-width:1100px){main{height:auto;grid-template-columns:1fr}.screen{min-height:420px}}
</style>
</head>
<body>
<header><div class="title">mOSdat Author Workbench</div><a class="nav" href="/">Runs</a><div class="spacer"></div><span id="author-status" class="status">no session</span></header>
<main>
  <section class="panel"><div class="panel-head"><strong>Session</strong></div><div class="panel-body">
    <label class="small">VM</label><select id="author-vm" onchange="authorUpdateVmStatus()"><option value="">Loading VMs...</option></select><div id="author-vm-status" class="status unknown">unknown</div>
    <div class="row"><button class="primary" data-op onclick="authorStart()">Start</button><button data-op onclick="authorCapture()">Refresh screen</button></div>
    <div id="author-op" class="op-card" role="status" aria-live="polite"><div class="spinner"></div><div><div id="author-op-title" class="op-title">Ready</div><div id="author-op-detail" class="op-detail">Select a command to run.</div></div></div>
    <label class="small">Prompt / question</label><textarea id="author-prompt" placeholder="find the login button"></textarea>
    <div class="row"><button data-op onclick="authorLocalize()">Localize</button><button data-op onclick="authorVerify()">Verify</button></div>
    <button data-op onclick="authorDescribeTarget()">Describe clicked target</button>
    <div class="small">Actions require manual confirm.</div>
    <div class="row"><button data-op onclick="authorHover()">Hover</button><button data-op onclick="authorClick('left')">Left click</button><button data-op onclick="authorClick('right')">Right click</button></div>
    <label class="small">Text</label><input id="author-type" placeholder="text to type"><button data-op onclick="authorType()">Run confirmed type</button>
    <label class="small">Key</label><input id="author-key" placeholder="key, e.g. enter"><button data-op onclick="authorKey()">Run confirmed key</button>
    <label class="small">Wait seconds</label><input id="author-wait" type="number" min="0" max="10" value="1"><button data-op onclick="authorWait()">Run confirmed wait</button>
    <label class="small">Shell command</label><textarea id="author-shell" placeholder="shell command"></textarea><button data-op onclick="authorShell()">Run confirmed shell</button>
    <label class="small">Launch command</label><input id="author-launch" placeholder="app launch command"><label class="small">Launch wait seconds</label><input id="author-launch-wait" type="number" min="0" max="60" value="0"><button data-op onclick="authorLaunch()">Run confirmed launch</button>
    <button data-op onclick="authorValidate()">Validate draft</button>
    <button data-op onclick="authorClose()">Close session</button>
  </div></section>
  <section class="screen" id="author-screen"><span class="small">capture appears here</span></section>
  <section class="panel"><div class="panel-head"><strong>Output</strong><button data-op onclick="authorExport()">Export YAML</button></div><div class="panel-body">
    <div class="small">VLM result</div><pre id="author-result">{}</pre>
    <div class="small">Draft YAML</div><pre id="author-draft">steps: []</pre>
    <div class="small">Draft steps JSON editor</div><textarea id="author-steps-json" placeholder='[{"key":"escape"}]'></textarea>
    <div class="row"><button data-op onclick="authorLoadStepsEditor()">Load steps</button><button data-op onclick="authorReplaceSteps()">Replace steps</button><button data-op onclick="authorAppendStep()">Append step</button></div>
  </div></section>
</main>
<script>
let authorSession=null;let authorTarget=null;let authorVms=[];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function postJson(url,payload){const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok||data.error)throw new Error(data.error||res.statusText);return data}
async function fetchJson(url){const res=await fetch(url,{cache:'no-store'});const data=await res.json();if(!res.ok||data.error)throw new Error(data.error||res.statusText);return data}
function authorSetStatus(text,kind=''){const el=document.getElementById('author-status');el.textContent=text;el.className=`status ${kind}`.trim()}
function authorOpCard(){return document.getElementById('author-op')}
function authorSetBusy(isBusy,title='',detail=''){
  document.body.classList.toggle('author-busy',isBusy);
  document.querySelectorAll('button[data-op]').forEach(btn=>btn.disabled=isBusy);
  const screen=document.getElementById('author-screen');
  if(screen){screen.classList.toggle('busy',isBusy);if(isBusy)screen.dataset.busy=`${title} — waiting for dashboard response`;else delete screen.dataset.busy;}
  if(isBusy)authorSetStatus(title,'busy');
  const card=authorOpCard();if(!card)return;
  if(isBusy){card.className='op-card active';document.getElementById('author-op-title').textContent=title;document.getElementById('author-op-detail').textContent=detail||'Request sent. Waiting for response…';}
}
function authorSetOpDone(title,detail='Done'){const card=authorOpCard();if(card){card.className='op-card done';document.getElementById('author-op-title').textContent=title;document.getElementById('author-op-detail').textContent=detail;}authorSetStatus(detail,'running')}
function authorSetOpError(title,error){const message=error?.message||String(error);const card=authorOpCard();if(card){card.className='op-card error';document.getElementById('author-op-title').textContent=`${title} failed`;document.getElementById('author-op-detail').textContent=message;}authorSetStatus(message,'unknown')}
async function authorRun(title,detail,fn){authorSetBusy(true,title,detail);const started=performance.now();try{const result=await fn();const elapsed=Math.max(0,Math.round(performance.now()-started));authorSetOpDone(title,`Done in ${(elapsed/1000).toFixed(1)}s`);return result}catch(e){authorSetOpError(title,e);return null}finally{authorSetBusy(false)}}
function authorShow(obj){document.getElementById('author-result').textContent=JSON.stringify(obj,null,2)}
function authorDraft(steps){const safe=steps||[];document.getElementById('author-draft').textContent='steps:\n'+safe.map(s=>'  - '+JSON.stringify(s)).join('\n');const editor=document.getElementById('author-steps-json');if(editor&&!editor.value.trim())editor.value=JSON.stringify(safe,null,2)}
function authorVmIcon(vm){if(vm.status==='running')return '●';if(vm.status==='stopped')return '○';return '?'}
function authorUpdateVmStatus(){const name=document.getElementById('author-vm').value;const vm=authorVms.find(v=>v.name===name);const pill=document.getElementById('author-vm-status');if(!vm){pill.textContent='unknown';pill.className='status unknown';return}pill.textContent=`${authorVmIcon(vm)} ${vm.status} / ${vm.desktop} / vmid ${vm.vmid}`;pill.className=`status ${vm.status==='running'?'running':vm.status==='stopped'?'stopped':'unknown'}`}
async function authorLoadVms(){try{const data=await fetchJson('/api/author/vms');authorVms=data.vms||[];const sel=document.getElementById('author-vm');if(!data.configured){sel.innerHTML='<option value="">start live with --config</option>';authorSetStatus('authoring requires --config','unknown');authorUpdateVmStatus();return}sel.innerHTML=authorVms.length?authorVms.map(vm=>`<option value="${esc(vm.name)}">${authorVmIcon(vm)} ${esc(vm.name)}</option>`).join(''):'<option value="">no VMs configured</option>';authorUpdateVmStatus()}catch(e){authorSetOpError('Load VMs',e)}}
async function authorEnsureSession(){if(authorSession)return authorSession;const vmName=document.getElementById('author-vm').value;if(!vmName)throw new Error('select a VM first');const vm=authorVms.find(v=>v.name===vmName);if(vm&&vm.status!=='running')throw new Error(`${vmName} is ${vm.status}; start it before authoring`);authorSetStatus(`creating session / ${vmName}`,'busy');const data=await postJson('/api/author/session',{vm:vmName});authorSession=data.session_id;authorSetStatus(`session ${authorSession} / ${data.vm}`,'running');authorDraft(data.draft_steps);return authorSession}
async function authorStart(){await authorRun('Starting session','Opening VNC and preparing authoring state…',async()=>{authorSession=null;await authorEnsureSession();await authorCapture(false)})}
async function authorCapture(wrap=true){const work=async()=>{const session=await authorEnsureSession();const data=await fetchJson(`/api/author/screenshot?session=${encodeURIComponent(session)}`);const screen=document.getElementById('author-screen');screen.innerHTML=`<img id="author-img" src="data:${data.content_type};base64,${data.image}">`;const img=document.getElementById('author-img');img.addEventListener('click',authorPickTarget);authorShow({width:data.width,height:data.height,manual_pick:'click screenshot to set target, then describe it or run an action'});return data};return wrap?authorRun('Refreshing screen','Capturing the latest VNC framebuffer…',work):work()}
function authorPickTarget(ev){const img=document.getElementById('author-img');if(!img)return;const rect=img.getBoundingClientRect();const x=Math.round(((ev.clientX-rect.left)/rect.width)*img.naturalWidth);const y=Math.round(((ev.clientY-rect.top)/rect.height)*img.naturalHeight);authorTarget={prompt:'manual target',x,y,width:img.naturalWidth,height:img.naturalHeight,source:'manual'};authorShow(authorTarget);authorPlaceTarget(authorTarget);authorSetOpDone('Target selected',`Selected ${x},${y}. Describe it or run an action.`)}
function authorPlaceTarget(data){document.querySelectorAll('.target').forEach(el=>el.remove());const img=document.getElementById('author-img');const screen=document.getElementById('author-screen');if(!img||!screen)return;const ir=img.getBoundingClientRect();const sr=screen.getBoundingClientRect();const width=data.width||img.naturalWidth;const height=data.height||img.naturalHeight;if(!width||!height)return;const dot=document.createElement('div');dot.className='target';dot.style.left=`${ir.left-sr.left+(data.x/width)*ir.width}px`;dot.style.top=`${ir.top-sr.top+(data.y/height)*ir.height}px`;screen.appendChild(dot)}
async function authorLocalize(){await authorRun('Localizing prompt','VLM is finding the described target on the current screen…',async()=>{const session=await authorEnsureSession();const prompt=document.getElementById('author-prompt').value;const data=await postJson('/api/author/vlm/localize',{session_id:session,prompt});authorTarget=data;authorShow(data);authorPlaceTarget(data);return data})}
async function authorDescribeTarget(){await authorRun('Describing clicked target','VLM is turning the selected coordinate into a reusable prompt…',async()=>{const session=await authorEnsureSession();if(!authorTarget)throw new Error('click screenshot first');const data=await postJson('/api/author/vlm/describe',{session_id:session,x:authorTarget.x,y:authorTarget.y});authorTarget=data;document.getElementById('author-prompt').value=data.prompt||'';authorShow(data);authorPlaceTarget(data);return data})}
async function authorVerify(){await authorRun('Verifying screen','VLM is answering the yes/no screen question…',async()=>{const session=await authorEnsureSession();const question=document.getElementById('author-prompt').value;authorShow(await postJson('/api/author/vlm/verify',{session_id:session,question}))})}
async function authorAfterAction(data){authorDraft(data.draft_steps);authorShow(data);authorTarget=null;await authorCapture(false)}
async function authorHover(){await authorRun('Running hover','Injecting pointer movement, then refreshing the screen…',async()=>{const session=await authorEnsureSession();if(!authorTarget)throw new Error('localize first');const data=await postJson('/api/author/action',{session_id:session,action:'hover',confirm:true,x:authorTarget.x,y:authorTarget.y,prompt:authorTarget.prompt});await authorAfterAction(data)})}
async function authorClick(button){await authorRun(`Running ${button} click`,'Injecting click, then refreshing the screen…',async()=>{const session=await authorEnsureSession();if(!authorTarget)throw new Error('localize first');const data=await postJson('/api/author/action',{session_id:session,action:'click',button,confirm:true,x:authorTarget.x,y:authorTarget.y,prompt:authorTarget.prompt});await authorAfterAction(data)})}
async function authorType(){await authorRun('Running type','Typing text into the focused field, then refreshing the screen…',async()=>{const session=await authorEnsureSession();const text=document.getElementById('author-type').value;const data=await postJson('/api/author/action',{session_id:session,action:'type',confirm:true,text});await authorAfterAction(data)})}
async function authorKey(){await authorRun('Running key press','Sending key input, then refreshing the screen…',async()=>{const session=await authorEnsureSession();const key=document.getElementById('author-key').value;const data=await postJson('/api/author/action',{session_id:session,action:'key',confirm:true,key});await authorAfterAction(data)})}
async function authorWait(){await authorRun('Running wait','Waiting intentionally before refreshing the screen…',async()=>{const session=await authorEnsureSession();const seconds=Number(document.getElementById('author-wait').value||1);const data=await postJson('/api/author/action',{session_id:session,action:'wait',confirm:true,seconds});await authorAfterAction(data)})}
async function authorShell(){await authorRun('Running shell command','Executing command inside the guest/session context…',async()=>{const session=await authorEnsureSession();const cmd=document.getElementById('author-shell').value;if(!cmd)throw new Error('shell command required');const data=await postJson('/api/author/action',{session_id:session,action:'shell',confirm:true,cmd});await authorAfterAction(data)})}
async function authorLaunch(){await authorRun('Running launch command','Launching application and waiting for requested settle time…',async()=>{const session=await authorEnsureSession();const cmd=document.getElementById('author-launch').value;if(!cmd)throw new Error('launch command required');const wait=Number(document.getElementById('author-launch-wait').value||0);const data=await postJson('/api/author/action',{session_id:session,action:'launch',confirm:true,cmd,wait});await authorAfterAction(data)})}
async function authorValidate(){await authorRun('Validating draft','Checking the authored YAML through the scenario parser…',async()=>{const session=await authorEnsureSession();authorShow(await postJson('/api/author/validate',{session_id:session}))})}
async function authorClose(){await authorRun('Closing session','Closing the VNC-backed authoring session…',async()=>{if(!authorSession)throw new Error('no session to close');const closed=authorSession;authorShow(await postJson('/api/author/close',{session_id:authorSession}));authorSession=null;authorTarget=null;authorSetStatus(`closed ${closed}`)})}
async function authorLoadStepsEditor(){await authorRun('Loading draft steps','Fetching the current authored draft…',async()=>{const session=await authorEnsureSession();const data=await fetchJson(`/api/author/session?session=${encodeURIComponent(session)}`);document.getElementById('author-steps-json').value=JSON.stringify(data.draft_steps||[],null,2);authorShow(data)})}
async function authorReplaceSteps(){await authorRun('Replacing draft steps','Saving edited draft step JSON…',async()=>{const session=await authorEnsureSession();const steps=JSON.parse(document.getElementById('author-steps-json').value||'[]');if(!Array.isArray(steps))throw new Error('steps editor must contain a JSON array');const data=await postJson('/api/author/step',{session_id:session,steps});authorDraft(data.draft_steps);authorShow(data)})}
async function authorAppendStep(){await authorRun('Appending draft step','Adding one step to the authored draft…',async()=>{const session=await authorEnsureSession();const parsed=JSON.parse(document.getElementById('author-steps-json').value||'{}');const step=Array.isArray(parsed)?parsed[0]:parsed;if(!step||Array.isArray(step)||typeof step!=='object')throw new Error('append requires a JSON object or non-empty array');const data=await postJson('/api/author/step',{session_id:session,step});authorDraft(data.draft_steps);authorShow(data)})}
async function authorExport(){await authorRun('Exporting YAML','Rendering the current draft scenario YAML…',async()=>{const session=await authorEnsureSession();const res=await fetch(`/api/author/export?session=${encodeURIComponent(session)}`);const text=await res.text();if(!res.ok)throw new Error(text||res.statusText);document.getElementById('author-draft').textContent=text})}
authorLoadVms();
</script>
</body>
</html>
"""
